export const DEFAULT_CONTENT: Record<string, any> = {
  nav: {
    tagline: 'Defining every pixel with precision',
    cta: 'Get Free Demo',
    links: [
      { label: 'Services', href: '#services' },
      { label: 'Work', href: '#work' },
      { label: 'Pricing', href: '#pricing' },
      { label: 'About', href: '#about' },
      { label: 'Contact', href: '#contact' },
    ],
  },
  hero: {
    eyebrow: 'Finpixel India · Bihar to Bharat',
    title: 'We Build Brands, Not Just Websites.',
    subheadline: 'We build high-performance websites for Schools, Colleges, Hotels, Restaurants and Brands across India. Fast. Secure. Affordable.',
    primary: 'Get Your Free Demo',
    secondary: 'See Our Work',
    assurances: ['Demo First, Pay After Approval', '100% Code Ownership'],
    floatingCards: [
      { label: 'Google Speed', value: '100 / 100' },
      { label: 'Pan-India', value: 'Remote-First' },
    ],
  },
  trust: {
    label: 'Our Guarantees',
    stats: [
      { value: '100', label: '% Hand-Coded' },
      { value: '48', label: 'hr First Draft' },
      { value: '100', label: '% Client Ownership' },
    ],
  },
  services: {
    eyebrow: 'What We Build',
    headline: 'Precision-Crafted Digital Products',
    subheadline: 'No slow website builders. No bloated themes. Every line of code written by hand for raw speed, security, and conversion.',
    items: [
      {
        eyebrow: '01 — Websites',
        title: 'Hand-Coded Premium Websites',
        description: 'Clean HTML, CSS & JavaScript. No WordPress, no Wix bloat. Optimised for PageSpeed 100, technical SEO, and actual business conversions.',
        badge: 'PageSpeed 100 · Free SSL · Mobile-First',
        cta: 'Start a website project',
        interest: 'Website',
        visual: 'browser',
      },
      {
        eyebrow: '02 — Hosting & Security',
        title: 'Zero-Maintenance Global Hosting',
        description: 'We handle your domain, DNS records, automated SSL certificates, and lightning-fast CDN deployment so you never have to manage a server.',
        badge: '99.99% Uptime · DDoS Protected · Automated Backups',
        cta: 'Talk about hosting',
        interest: 'Hosting',
        visual: 'security',
      },
      {
        eyebrow: '03 — Growth & Automation',
        title: 'Conversion & Growth Systems',
        description: 'Hyper-local Google Maps SEO, social media growth engineering, automated lead capture, and workflow bots that turn visitors into paying clients.',
        badge: 'Local SEO · Lead Funnel · n8n Automation',
        cta: 'Grow my business',
        interest: 'Growth',
        visual: 'analytics',
      },
    ],
  },
  comparison: {
    eyebrow: 'Why Finpixel',
    headline: 'The Smarter Choice for Indian Businesses',
    subheadline: 'See how Finpixel compares directly against DIY builders and generic bloated agencies.',
    criteriaLabel: 'Criteria',
    winnerLabel: 'Finpixel Advantage',
    columns: [
      { name: 'Finpixel India', note: 'Hand-coded studio', featured: true },
      { name: 'Wix / WordPress', note: 'DIY / Bloated builder' },
      { name: 'Generic Agencies', note: 'Overpriced template shop' },
    ],
    rows: [
      { label: 'PageSpeed Score', note: 'Crucial for SEO & mobile conversions', values: [{ positive: true, text: '98–100 / 100' }, { positive: false, text: '35–65 (Slow)' }, { positive: false, text: '50–75 (Average)' }] },
      { label: 'Code Architecture', note: 'Clean, hand-written HTML5/CSS/JS', values: [{ positive: true, text: '100% Hand-Crafted' }, { positive: false, text: 'Heavy Plugin Bloat' }, { positive: false, text: 'Stock Theme Copies' }] },
      { label: 'Code Ownership', note: 'You own the full source code forever', values: [{ positive: true, text: 'Full Ownership' }, { positive: false, text: 'Locked in Platform' }, { positive: false, text: 'Annual Lock-in' }] },
      { label: 'Trust First Delivery', note: 'See your complete website before paying', values: [{ positive: true, text: 'Demo First, Pay Later' }, { positive: false, text: 'Pay 100% Upfront' }, { positive: false, text: '50% Non-refundable' }] },
      { label: 'Local SEO & Maps', note: 'Dominate near-me searches in your city', values: [{ positive: true, text: 'Built-in & Verified' }, { positive: false, text: 'Limited / Manual' }, { positive: false, text: 'Expensive Add-on' }] },
    ],
  },
  industries: {
    eyebrow: 'Who We Serve',
    headline: 'Engineered for Bharat’s Backbone',
    subheadline: 'From local educational institutions to pan-India modern brands — we empower real organisations.',
    items: [
      { icon: 'graduation', label: 'Education', title: 'Schools & Colleges', description: 'Admissions-focused websites with online fee inquiries, modern photo galleries, and principal notice boards.' },
      { icon: 'hotel', label: 'Hospitality', title: 'Hotels & Resorts', description: 'Direct booking interfaces, high-res visual room tours, and zero-commission reservation flows.' },
      { icon: 'health', label: 'Healthcare', title: 'Clinics & Hospitals', description: 'Trust-inspiring doctor portals with instant appointment WhatsApp booking and Google Maps patient directions.' },
      { icon: 'coffee', label: 'Food & Dining', title: 'Restaurants & Cafés', description: 'Interactive mobile menus, reservation funnels, and Instagram-integrated digital showcases that pack tables.' },
      { icon: 'retail', label: 'Retail & Commerce', title: 'Shops & Showrooms', description: 'Premium local presence, catalog presentations, and verified local Google Business Profile integration.' },
      { icon: 'startup', label: 'Technology', title: 'Startups & Brands', description: 'Ultra-fast, high-converting product landing pages engineered to validate demand and impress investors.' },
    ],
  },
  promise: {
    eyebrow: 'Our Guarantees',
    headline: 'The Finpixel Promise',
    subheadline: 'Four foundational rules that protect your investment and guarantee satisfaction.',
    items: [
      { icon: 'shield', title: 'Demo First, Pay After Approval', description: 'We build a working first draft of your website before you pay a single rupee. Complete peace of mind.' },
      { icon: 'code', title: '100% Code & Asset Ownership', description: 'Your domain, your code repository, your designs. Everything belongs to you with zero hidden lock-in.' },
      { icon: 'maps', title: 'Guaranteed 95+ PageSpeed', description: 'Raw, hand-written code means your website loads in under 1 second, even on standard mobile networks.' },
      { icon: 'coffee', title: 'Direct WhatsApp Line', description: 'No ticketing queues or customer support bureaucracy. Direct access to our engineering team anytime.' },
    ],
  },
  process: {
    eyebrow: 'How It Works',
    headline: 'From Idea to Live Site',
    subheadline: 'A simple, transparent process with no surprises.',
    steps: [
      {
        timing: 'Day 1',
        phase: 'Phase 01',
        title: 'Discovery & Vision',
        description: 'Tell us about your business, target audience, and goals. We map out structure, features, and visual hierarchy.',
        deliverable: 'Scope Blueprint & Architecture',
        highlight: '20-Min Strategy Call',
      },
      {
        timing: 'Day 2–3',
        phase: 'Phase 02',
        title: 'Hand-Coded Working Demo',
        description: 'We code your live prototype by hand with clean HTML, CSS, and React. You see real interactive progress on a live link.',
        deliverable: 'Private Live Preview Link',
        highlight: '48-Hour Working Prototype',
      },
      {
        timing: 'Day 4–6',
        phase: 'Phase 03',
        title: 'Your Direct Feedback',
        description: 'Test your site across phone, tablet, and PC. We refine animations, layout spacing, and copy until you are thrilled.',
        deliverable: 'Zero-Friction Revisions',
        highlight: 'Pixel-Perfect Polish',
      },
      {
        timing: 'Day 7 / Approval',
        phase: 'Phase 04',
        title: 'Pay & Go Live',
        description: 'Pay only after you approve the final product. We connect your custom domain, set up SSL, and deploy to Cloudflare CDN.',
        deliverable: 'Global CDN, SSL & 100% Code',
        highlight: 'Cloudflare Deployment',
      },
    ],
  },
  pricing: {
    eyebrow: 'Simple Pricing',
    headline: 'Plans for Every Budget',
    subheadline: 'Transparent pricing. No hidden fees. Final cost based on your scope.',
    note: 'All plans include Demo-First guarantee. Pay only after you review and approve your working website.',
    popularBadge: 'Most Popular · Best Value',
    plans: [
      {
        subtitle: 'Starter · Local Presence',
        name: 'Launch',
        price: '7,499',
        currency: '₹',
        period: 'onwards',
        description: 'Perfect for local schools, clinics, restaurants, and retail shops getting their first high-performance web presence.',
        featured: false,
        interest: 'Launch Plan',
        cta: 'Request Launch Demo',
        idealFor: 'Schools, Clinics & Shops',
        features: [
          'Up to 5 hand-coded custom pages',
          'PageSpeed 95+ performance guarantee',
          'Mobile-first responsive architecture',
          'Instant WhatsApp enquiry trigger',
          'Google Maps & Local SEO setup',
          'Free SSL & Cloudflare CDN hosting',
          '100% source code ownership',
        ],
      },
      {
        subtitle: 'Most Popular · Growth Engine',
        name: 'Growth',
        price: '14,999',
        currency: '₹',
        period: 'onwards',
        description: 'Engineered for colleges, multi-specialty hospitals, luxury hotels, and ambitious commercial businesses needing real lead flow.',
        featured: true,
        interest: 'Growth Plan',
        cta: 'Request Growth Demo',
        idealFor: 'Colleges, Hospitals & Resorts',
        features: [
          'Up to 10 hand-coded custom pages',
          'PageSpeed 100 benchmark score',
          'Interactive enquiry & lead capture system',
          'Hyper-local Google Maps dominance setup',
          'Photo/video media showcase & notice boards',
          'WhatsApp instant lead notifications',
          '3 months priority maintenance & support',
          'Full code ownership & Git repository',
        ],
      },
      {
        subtitle: 'Enterprise · Custom Digital Suite',
        name: 'Scale',
        price: '24,999',
        currency: '₹',
        period: 'onwards',
        description: 'Full custom digital ecosystem for institutions, expanding startups, and high-volume brands requiring custom flows.',
        featured: false,
        interest: 'Scale Plan',
        cta: 'Request Scale Demo',
        idealFor: 'Institutions, Startups & Brands',
        features: [
          'Unlimited custom hand-coded pages',
          'Custom web application & portal features',
          'Advanced technical SEO & conversion funnel',
          'Social media & marketing workflow setup',
          'n8n / AI auto-responder integration',
          '6 months dedicated developer support',
          'Priority direct WhatsApp access',
          'Full code ownership & IP assignment',
        ],
      },
    ],
  },
  about: {
    eyebrow: 'We Are Finpixel India',
    headline: 'The Digital Architects of Bharat',
    tagline: 'Bridging traditional Bharat with the digital future through uncompromising hand-crafted technology.',
    who: {
      title: 'Who We Are',
      paragraphs: [
        'Finpixel India is not your typical corporate agency. We are an agile, remote-first technology studio born out of a simple necessity: Local businesses deserve world-class digital tools.',
        'Founded by Ashish Singh (Tech Lead) and the team, we operate from the heart of Bihar with a Pan-India vision. We are the bridge between the traditional "brick-and-mortar" India and the explosive "Digital India" of tomorrow. While big city agencies chase million-dollar contracts, we are busy empowering the schools, hospitals, and businesses that actually build our nation.',
      ],
    },
    vision: {
      title: 'Our Vision',
      description: 'To democratize premium web technology. We believe a small private school in a village should have a website that is just as fast, secure, and professional as a top university in Mumbai.',
    },
    goal: {
      title: 'Our Goal',
      description: "To digitize 1,000 local institutions across India by 2027. We aren't just building websites; we are building Digital Assets that solve real business problems—increasing admissions for schools, patient trust for doctors, and footfall for local brands.",
    },
    whatWeDo: {
      title: 'High-Performance Static Web Development',
      subtitle: 'Pure engineering with zero builder overhead',
      items: [
        {
          title: 'Hand-Coded Perfection',
          description: 'We do not use slow, bloated website builders like Wix or WordPress. We write raw, clean HTML5, CSS3, and JavaScript. This means our sites load in under 1 second, even on 4G mobile networks.',
          icon: 'code',
        },
        {
          title: 'School & College Ecosystems',
          description: 'We build digital infrastructures for education—admission inquiry portals, mobile-responsive galleries, and notice boards that principals can actually use.',
          icon: 'graduation',
        },
        {
          title: 'Hyper-Local SEO & Maps',
          description: 'A website is useless if no one can find it. We specialize in Google Maps Optimization, ensuring our clients dominate the "Near Me" searches in their districts.',
          icon: 'maps',
        },
        {
          title: 'Zero-Maintenance Hosting',
          description: 'By leveraging global CDNs (Content Delivery Networks) like Netlify and Cloudflare, we ensure 99.99% uptime with military-grade SSL security, all without forcing expensive server costs on our clients.',
          icon: 'hosting',
        },
      ],
    },
    strengths: {
      title: 'Our Unmatched Strengths',
      items: [
        {
          title: "1. The 'Trust First' Model (Our Secret Weapon)",
          description: "In an industry full of scams and over-promising, we flipped the script. We operate on a 'Demo First, Pay Later' philosophy. We build a working prototype of the client's website before we ask for a single rupee. We don't demand trust; we earn it.",
        },
        {
          title: "2. The 'Spiderman' Agility",
          description: "We run lean. We don't have bloated teams or fancy offices. Using advanced AI-augmented coding workflows (Gemini/Antigravity), we can deploy a full-scale commercial website in 48 hours—something traditional agencies take weeks to do.",
        },
        {
          title: "3. The 'Local Empathy' Advantage",
          description: "We understand the Indian market. We know that a local business in India cares more about trust (Bharosa) and value than technical jargon. We speak their language, offering solutions that fit their budget without compromising on the 'Big City' quality.",
        },
        {
          title: "4. 100/100 Performance Obsession",
          description: "We are obsessed with the Google PageSpeed Score. While competitors deliver heavy sites that score a '40/100' and lose customers, we aim for a perfect 100/100. We treat speed as a feature, not an afterthought.",
        },
      ],
    },
    otherWork: {
      title: 'Our Other Precise Works',
      intro: 'Beyond websites, we engineer growth using Influence and Automation.',
      items: [
        {
          service: 'Social Media Promotion',
          trapLabel: 'The Visibility Trap',
          trapTitle: "The 'Ghost Town' Feed",
          quote: '"Posting every single day but nobody cares? You are shouting in an empty room."',
          solutionLabel: 'The Solution',
          solutionTitle: 'Viral Engineering',
          solution: "We don't guess algorithms; we master them. We turn your social media into a traffic engine that drives real customers, not just random likes.",
        },
        {
          service: 'Social Media Promotion',
          trapLabel: 'The Aesthetic Trap',
          trapTitle: "Design by 'My Nephew'",
          quote: '"Ugly Canva posts ruin your brand reputation faster than a bad review ever could."',
          solutionLabel: 'The Solution',
          solutionTitle: 'Premium Brand Authority',
          solution: 'Your feed is your digital showroom. We curate a cohesive, high-end aesthetic that makes your brand look expensive, trustworthy, and unignorable.',
        },
        {
          service: 'Social Media Promotion',
          trapLabel: 'The ROI Trap',
          trapTitle: "'Likes' Don't Pay Bills",
          quote: '"Vanity metrics are fun to look at. Bank deposits are better to live with."',
          solutionLabel: 'The Solution',
          solutionTitle: 'Conversion Strategy',
          solution: 'We stop chasing hearts and start chasing leads. We align your content strategy to funnel users directly to your "Buy Now" button.',
        },
        {
          service: 'Automation & AI',
          trapLabel: 'The Data Trap',
          trapTitle: 'Excel Sheet Hell',
          quote: '"Still manually copying data from emails to spreadsheets? It’s 2026. Stop working like it\'s 1999."',
          solutionLabel: 'The Solution',
          solutionTitle: 'n8n Workflow Automation',
          solution: 'We build invisible robots that sync your data instantly. Form submission → CRM → WhatsApp → Invoice. Zero human effort required.',
        },
        {
          service: 'Automation & AI',
          trapLabel: 'The Speed Trap',
          trapTitle: 'Leads Going Cold',
          quote: '"If you take 6 hours to reply to a potential customer, they are already buying from your competitor."',
          solutionLabel: 'The Solution',
          solutionTitle: 'Instant AI Agents',
          solution: 'We deploy intelligent auto-responders that engage leads instantly, 24/7. Capture the customer while their interest is hot.',
        },
        {
          service: 'Automation & AI',
          trapLabel: 'The Accuracy Trap',
          trapTitle: 'Human Error is Expensive',
          quote: '"Typos in invoices? Missed follow-ups? Humans get tired and make mistakes."',
          solutionLabel: 'The Solution',
          solutionTitle: 'Flawless Execution',
          solution: "Robots don't need coffee breaks. We automate your boring repetitive tasks so you can focus on growing the business.",
        },
      ],
    },
    promise: {
      title: 'The Finpixel Promise',
      paragraphs: [
        "We are not just service providers; we are Co-Founders in our clients' digital journey. When a school works with Finpixel, they don't just get a URL. They get a 24/7 technical partner, a business growth consultant, and a team that takes their success personally.",
        'We are Finpixel India. We build the web, so you can build your business.',
      ],
    },
  },
  cta: {
    eyebrow: 'Ready to Transform Your Presence?',
    headline: "Let's Build Something Exceptional Together.",
    subheadline: 'Request your free interactive demo draft. Review it in 48 hours. Pay only when you are 100% satisfied.',
    primary: 'Get Your Free Demo',
    secondary: 'Chat on WhatsApp',
    proofs: ['Demo first, zero upfront payment', 'Working draft in 48 hours', '100% code & asset ownership'],
  },
  footer: {
    description: 'Finpixel India builds high-performance, hand-coded websites and automation systems for ambitious institutions and businesses across India. Demo first, pay after approval.',
    availability: 'Open for Pan-India Projects',
    navLabel: 'Navigation',
    contactLabel: 'Direct Contacts',
    socialLabel: 'Connect With Us',
    whatsapp: '+91 70041 76367',
    whatsappRaw: '917004176367',
    whatsappMessage: 'Hi Finpixel India! I visited your website and would like to request a free demo.',
    email: 'finpixelindia@gmail.com',
    location: 'Bihar · Pan-India Remote Studio',
    copyright: '© 2026 Finpixel India. Built with pride for Bharat.',
    links: [
      { label: 'Services', href: '#services' },
      { label: 'Work', href: '#work' },
      { label: 'Pricing', href: '#pricing' },
      { label: 'About', href: '#about' },
      { label: 'Contact', href: '#contact' },
    ],
    legal: [
      { label: 'Privacy Policy', href: '/privacy' },
    ],
    contactOptions: [
      { type: 'whatsapp', label: 'WhatsApp', value: '+91 70041 76367', href: 'https://wa.me/917004176367?text=Hello%20Finpixel%20India!%20I%20am%20interested%20in%20a%20free%20demo.' },
      { type: 'email', label: 'Email', value: 'finpixelindia@gmail.com', href: 'https://mail.google.com/mail/?view=cm&fs=1&to=finpixelindia@gmail.com' },
      { type: 'instagram', label: 'Instagram', value: '@finpixel.india', href: 'https://instagram.com/finpixel.india' },
      { type: 'linkedin', label: 'LinkedIn', value: 'Ashish Singh', href: 'https://www.linkedin.com/in/ashish-singh-9212563a3' },
      { type: 'fiverr', label: 'Fiverr', value: 'finpixelindia', href: 'https://www.fiverr.com/finpixelindia' },
      { type: 'x', label: 'X (Twitter)', value: '@Finpixelindia', href: 'https://x.com/Finpixelindia' },
      { type: 'github', label: 'GitHub', value: 'finpixel-india', href: 'https://github.com/finpixel-india' },
      { type: 'linktree', label: 'Linktree', value: 'linktr.ee/finpixelindia', href: 'https://linktr.ee/finpixelindia' },
      { type: 'notion', label: 'Portfolio', value: 'FinPixel India', href: 'https://www.notion.so/FinPixel-India-official-2dff04948ec9806ba968fdaab1925f53' },
    ],
  },
  leadForm: {
    eyebrow: 'Free Demo Request',
    title: "Let's Build Your Website",
    subheadline: "Fill in your details and we'll have a working first draft ready for you within 48 hours. Demo first, pay later.",
    error: 'We could not save your request automatically. Please message us on WhatsApp directly and we will begin immediately.',
    success: 'Your request is received! We will reach out to you on WhatsApp within a few hours.',
    sending: 'Submitting Query...',
    submit: 'Send Query',
    note: 'No payment before approval. 100% free first draft with no obligations.',
    fields: {
      name: 'Your Name',
      phone: 'WhatsApp Number',
      email: 'Email Address',
      business: 'Business / Industry',
      message: 'Project Details / Goal',
    },
    placeholders: {
      name: 'Ashish Singh',
      phone: '+91 70041 76367',
      email: 'finpixelindia@gmail.com',
      business: 'Select industry...',
      message: 'Tell us about your business, features you want, and your design ideas...',
    },
    businessTypes: [
      'School / College / Coaching',
      'Hotel / Resort / Guest House',
      'Clinic / Hospital / Pharmacy',
      'Restaurant / Café / Cloud Kitchen',
      'Shop / Mall / Retail Store',
      'Startup / Tech Product',
      'Corporate & Agency',
      'Personal Brand / Portfolio',
      'Other Services',
    ],
  },
  chatbot: {
    title: 'EDITH',
    subtitle: 'Finpixel AI Concierge',
    welcome: "Hi! I'm EDITH, Finpixel India's AI concierge. I can help you explore our hand-coded web design services, learn how our Demo First model works, or check pricing. How can I help you today?",
    placeholder: 'Ask EDITH anything about Finpixel…',
    error: 'EDITH encountered an issue. Please connect with the Finpixel team directly on WhatsApp.',
    note: 'EDITH is Finpixel India’s AI assistant. For project commitments, talk to our lead engineers directly on WhatsApp.',
    quickPrompts: [
      'How does Demo First, Pay Later work?',
      'What are your pricing plans?',
      'Why choose hand-coded over WordPress?',
      'Can you build for my school or hotel?',
    ],
  },
  privacy: {
    metaTitle: 'Privacy Policy — Finpixel India',
    brandNote: 'Privacy Policy',
    backLabel: 'Back to Home',
    eyebrow: 'Legal Document',
    title: 'Privacy Policy',
    intro: 'At Finpixel India, we are committed to protecting your personal information and your right to privacy. This policy explains how we collect, use, and safeguard your data when you visit our website or request our services.',
    effectiveLabel: 'Effective Date',
    effectiveDate: '01 September 2026',
    contentsLabel: 'Contents',
    callout: {
      title: 'Your Privacy Matters',
      description: 'We collect only what is necessary, never sell your data, and you retain full ownership of your information at all times.',
    },
    sections: [
      {
        title: 'Information We Collect',
        paragraphs: ['When you fill out our demo request form, we collect your name, phone number, email address, and business type to respond to your enquiry.', 'We may also collect basic analytics data (page views, device type) through privacy-respecting tools to improve our website.'],
        items: ['Name and contact details provided via our forms', 'Business type and project requirements', 'Basic technical data (browser type, country) via analytics'],
      },
      {
        title: 'How We Use Your Information',
        paragraphs: ['We use your information solely to respond to your demo request, communicate about our services, and deliver your project. We do not use your data for advertising or sell it to third parties.'],
        items: ['To respond to your enquiries and demo requests', 'To communicate project details and deliverables', 'To send important service-related updates (never spam)'],
      },
      {
        title: 'Data Storage & Security',
        paragraphs: ['Your data is stored securely with encrypted connections. Access is restricted to authorised personnel only. We retain enquiry data for up to 24 months unless you request deletion.'],
      },
      {
        title: 'Third-Party Services',
        paragraphs: ['We use WhatsApp Business for direct communication, and Cloudflare for hosting and DDoS protection. These services have their own privacy policies. We do not share your personal data with any other third parties.'],
        items: ['WhatsApp Business (Meta Platforms)', 'Cloudflare (hosting & security)', 'Supabase (secure database)'],
      },
      {
        title: 'Your Rights',
        paragraphs: ['You have the right to access, correct, or delete any personal data we hold about you. To exercise these rights, email us at finpixelindia@gmail.com. We will respond within 7 business days.'],
      },
      {
        title: 'Cookies',
        paragraphs: ['Our website uses only essential cookies to remember your theme preference (light/dark mode). We do not use advertising or tracking cookies. You can clear cookies anytime via your browser settings.'],
      },
      {
        title: 'Changes to This Policy',
        paragraphs: ['We may update this policy periodically. Changes will be posted on this page with an updated effective date. Continued use of our website after changes constitutes acceptance of the revised policy.'],
      },
    ],
    contact: {
      eyebrow: 'Questions?',
      title: 'Contact Us',
      description: 'If you have any questions about this Privacy Policy or how we handle your data, please reach out to us directly.',
      email: 'finpixelindia@gmail.com',
    },
    footer: '© 2026 Finpixel India. All rights reserved.',
  },
};
